config/routes.rb
Rails.application.routes.draw do
  resources :works

  get 'pages/index'

  root 'pages#index'

end

app/models/work.rb
class Work < ActiveRecord::Base
  has_attached_file :image,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :default_url => "http://placehold.it/#{:style}&text=Missing%20Image"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  @page_class = ''

  def index
    @page_class = 'index_nav'
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @works = Work.all
    respond_with(@works)
  end

  def show
    respond_with(@work)
  end

  def new
    @work = Work.new
    respond_with(@work)
  end

  def edit
  end

  def create
    @work = Work.new(work_params)
    @work.save
    respond_with(@work)
  end

  def update
    @work.update(work_params)
    respond_with(@work)
  end

  def destroy
    @work.destroy
    respond_with(@work)
  end

  private
    def set_work
      @work = Work.find(params[:id])
    end

    def work_params
      params.require(:work).permit(:title, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.slim
doctype html
html
  head
    title Chris Scott - Portfolio
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body{id="#{params[:controller]}" class="#{params[:action]}"}
    - if notice
      #notice = notice
    - if alert
      #alert = alert if alert
    = yield
    nav.navbar.navbar-fixed-bottom role="navigation"
      .container
        .row
          #nav{class="flexing #{@page_class}"}
            .btn-group.btn-group-lg.btn-group-justified
              = link_to 'Home', root_path, class:'btn'
              = link_to 'Work', works_path, class:'btn'
              = link_to 'Social', root_path, class:'btn'

app/views/pages/index.html.slim
.index-container
  .container
    .row
      .col-sm-6.col-md-4.hardcenter
        .text-center
          h1.cs
            | CS
          h5 style="font-size: 1.25em"
            | Designer / Developer
          h4 style="color: black"
            | Hi, my name is
            a href="#me" style="color:white"
              b  Chris
            |  and I love crafting clean and friendly user interfaces for web and devices.
        .text-center
          nav class="text-center st-multi-color st-shape-r5" style="font-size:125%;"
            a title="GitHub" class="st-icon-github" href=""
              span Github

app/views/works/_form.html.slim
= form_for @work, :html => { :multipart => true } do | f |
  - if @work.errors.any?
    #error_explanation
      h2 = "#{pluralize(@work.errors.count, "error")} prohibited this work from being saved:"
      ul
        - @work.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title

  .field
    = f.label :body
    = f.text_area :body

  .field
    = f.file_field :image

  .actions = f.submit

app/views/works/edit.html.slim
h1 Editing work

== render 'form'

= link_to 'Show', @work
'|
= link_to 'Back', works_path

app/views/works/index.html.slim
.container
  - @works.each do |work|
    /= work.title
    = work.body
    = link_to image_tag(work.image.url(:medium)), work
      /= link_to 'Edit', edit_work_path(work)
      /= link_to 'Destroy', work, data: {:confirm => 'Are you sure?'}, :method => :delete

      /= link_to 'New Work', new_work_path

app/views/works/new.html.slim
h1 New work

== render 'form'

= link_to 'Back', works_path

app/views/works/show.html.slim
.container
  .row
    .text-center
      = image_tag @work.image.url(:original), class:'work-img'

  .work-container
    .work-title = @work.title
    p
      strong Body:
      = @work.body

    = link_to 'Edit', edit_work_path(@work)
    '|
    = link_to 'Back', works_path